Importing libraries

In [1]:
import numpy as np
import pandas as pd

creating dataset

In [2]:
age = np.random.randint(1,100,100)
sal = np.random.randint(500,8000,100)
print(age)
print(sal)

[51 75 74 40 30 17 75 19 76 62 58 97 46 29 15 67 48 34 11 64  3 97 89 69
 39 84 77 60 67 76 15 33 33 23 65 63  7 56 46 97 59 73 40 66 70 27 37 95
 61 45 97 27 48 98 34  3 51 96 80 61 73 19 43  9 26 84 25 56  3 13 11 28
 48 47 52 35 91 28  7 93  2 61 72 72 64 38 33 90 19 12 74 91 55 49 58 90
 36 81 85 67]
[4438 3200 7607 7680 3415 6724 3138 5663 5794 1329 5932 1526 2364 4750
  784 6991 3882 4280 4155 4743 4366 5544  700 3656  801 5016 7297 4721
 2774 1139 5114 3513 5322 5677 1889 4605 4013 2576 1479 2023 6567 3621
 6879 6892 1673 7300 7637 4150 6845 5760 1598 7331 7727 2612 2983 6980
 1252 7988 7729 4216 4498 4584 1228 3073 2577 3462 5174 2792 5022 6675
 2469 2962 2619 3724 4530  782 6174 5573 6371 2894 2391 3375 3063 1661
 6753 5868  921 7699 1169  682 1587 7569 7143 7361 7536 3728 6282 3323
 5370 4215]


In [3]:
df = pd.DataFrame({"AGE" : age , "SALARY" : sal})
df

AGE  SALARY
0    51    4438
1    75    3200
2    74    7607
3    40    7680
4    30    3415
..  ...     ...
95   90    3728
96   36    6282
97   81    3323
98   85    5370
99   67    4215

[100 rows x 2 columns]

In [4]:
df['PURCHASED'] = 0
print(df)

    AGE  SALARY  PURCHASED
0    51    4438          0
1    75    3200          0
2    74    7607          0
3    40    7680          0
4    30    3415          0
..  ...     ...        ...
95   90    3728          0
96   36    6282          0
97   81    3323          0
98   85    5370          0
99   67    4215          0

[100 rows x 3 columns]


In [5]:
df['PURCHASED'] = df.apply(lambda x: 1 if (6*x['AGE']+3*x["SALARY"]>18000)  else 0, axis=1)
print(df)

    AGE  SALARY  PURCHASED
0    51    4438          0
1    75    3200          0
2    74    7607          1
3    40    7680          1
4    30    3415          0
..  ...     ...        ...
95   90    3728          0
96   36    6282          1
97   81    3323          0
98   85    5370          0
99   67    4215          0

[100 rows x 3 columns]


Introducing error

In [6]:
df['AGE'] = df['AGE'] + np.random.randint(0 , 33, 100)
df['SALARY'] = df['SALARY'] + np.random.randint(500, 1000, 100)
df

AGE  SALARY  PURCHASED
0    71    5052          0
1    97    3895          0
2    77    8575          1
3    44    8374          1
4    41    4402          0
..  ...     ...        ...
95   91    4461          0
96   61    7221          1
97   94    4310          0
98  116    5904          0
99   87    4815          0

[100 rows x 3 columns]

Saving and importing dataset

In [7]:
df.to_csv('Age_Salary.csv' , index = 0)

In [11]:
dataset = pd.read_csv('Age_Salary.csv')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values
X


array([[  71, 5052],
       [  97, 3895],
       [  77, 8575],
       [  44, 8374],
       [  41, 4402],
       [  43, 7572],
       [  76, 3988],
       [  26, 6215],
       [  98, 6601],
       [  79, 1976],
       [  81, 6725],
       [ 105, 2266],
       [  54, 3242],
       [  30, 5258],
       [  19, 1598],
       [  86, 7966],
       [  52, 4635],
       [  37, 5248],
       [  14, 5063],
       [  73, 5502],
       [  17, 5188],
       [ 118, 6509],
       [  91, 1584],
       [  69, 4603],
       [  60, 1458],
       [  95, 5710],
       [  94, 8279],
       [  77, 5499],
       [  70, 3278],
       [  98, 2128],
       [  30, 6091],
       [  65, 4282],
       [  54, 6282],
       [  32, 6524],
       [  92, 2703],
       [  78, 5357],
       [  20, 4848],
       [  88, 3345],
       [  72, 2300],
       [ 102, 2987],
       [  90, 7237],
       [  89, 4551],
       [  45, 7722],
       [  71, 7732],
       [  97, 2176],
       [  46, 8205],
       [  60, 8606],
       [ 112,

Splitting the dataset into the Training set and Test set

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [13]:
print(X_train)
print(y_train)
print(X_test)
print(y_test)

[[  65 7551]
 [  76 3988]
 [  87 4815]
 [  87 3637]
 [  98 6720]
 [  86 5113]
 [  27 2989]
 [  78 2376]
 [  10 5775]
 [  47 8267]
 [  77 5499]
 [  14 5063]
 [  59 2040]
 [  29 3822]
 [  62 5060]
 [  97 3895]
 [  20 5397]
 [  45 7722]
 [  89 4551]
 [  41 4402]
 [  86 7966]
 [  37 5248]
 [  90 7237]
 [  72 2300]
 [  43 7572]
 [ 120 8399]
 [  68 4929]
 [  71 5052]
 [  92 2703]
 [  70 3278]
 [ 114 2169]
 [ 105 2266]
 [  78 5357]
 [  69 4603]
 [  62 8229]
 [  81 6725]
 [  65 4282]
 [  25 5936]
 [ 117 8583]
 [ 123 3583]
 [  46 6593]
 [  54 6282]
 [  94 7265]
 [  19 1598]
 [  27 1240]
 [  73 5502]
 [  98 2128]
 [  77 6274]
 [  94 4310]
 [ 116 5904]
 [  38 7451]
 [  17 5188]
 [  74 8037]
 [  65 3258]
 [  46 6239]
 [  95 5710]
 [  88 3345]
 [  62 4259]
 [  60 8606]
 [ 102 2987]
 [ 102 4163]
 [  88 8246]
 [  54 3242]
 [  28 2049]
 [  42 3335]
 [ 121 8467]
 [  20 4848]
 [ 118 6509]
 [  82 2649]
 [  79 1976]
 [  61 7221]
 [  59 3701]
 [  58 3569]
 [ 112 4754]
 [  97 2176]]
[1 0 0 0 1 0 0 0 0 1 0 0

Feature Scaling

In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)

[[-1.69755218e-01  1.26844293e+00]
 [ 2.05708736e-01 -4.95639725e-01]
 [ 5.81172689e-01 -8.61824269e-02]
 [ 5.81172689e-01 -6.69423899e-01]
 [ 9.56636643e-01  8.57005183e-01]
 [ 5.47039603e-01  6.13608317e-02]
 [-1.46681251e+00 -9.90256220e-01]
 [ 2.73974909e-01 -1.29375963e+00]
 [-2.04707499e+00  3.89124715e-01]
 [-7.84150778e-01  1.62294284e+00]
 [ 2.39841822e-01  2.52473912e-01]
 [-1.91054264e+00  3.66052514e-02]
 [-3.74553738e-01 -1.46011713e+00]
 [-1.39854634e+00 -5.77828252e-01]
 [-2.72154478e-01  3.51199166e-02]
 [ 9.22503556e-01 -5.41685105e-01]
 [-1.70574412e+00  2.01972528e-01]
 [-8.52416952e-01  1.35310701e+00]
 [ 6.49438863e-01 -2.16891891e-01]
 [-9.88949298e-01 -2.90663520e-01]
 [ 5.47039603e-01  1.47391424e+00]
 [-1.12548165e+00  1.28200899e-01]
 [ 6.83571949e-01  1.11297788e+00]
 [ 6.91763890e-02 -1.33138812e+00]
 [-9.20683125e-01  1.27884027e+00]
 [ 1.70756455e+00  1.68829757e+00]
 [-6.73559577e-02 -2.97397038e-02]
 [ 3.50433023e-02  3.11590238e-02]
 [ 7.51838123e-01 -1

Training the Logistic Regression model on the Training set

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

Predicting a new result

In [17]:
print(classifier.predict(sc.transform([[45,6000]])))

[0]


Predicting the Test set results

In [20]:
y_pred = classifier.predict(X_test)
y_pred

array([1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1], dtype=int64)

In [21]:
print("Predict Actual")
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

Predict Actual
[[1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]]


In [22]:
print("Pred Actual")
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

Pred Actual
[[1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]]


Making the Confusion Matrix

In [23]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)

print(cm)
accuracy_score(y_test, y_pred)

[[16  0]
 [ 0  9]]


1.0

In [24]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
len(y_pred)
y_pred.shape

[[1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]]


(25,)

In [25]:
from sklearn.metrics import accuracy_score
print("Accuracy is: " ,round(accuracy_score(y_test, y_pred),2)*100, "%")

Accuracy is:  100.0 %
